### ISSUE TITLE
java.lang.NoClassDefFoundError when using jwt-circe with http4s

### ISSUE THREAD

**Issue by marko-asplund** [jwt-scala/jwt-scala#138]
I'm running into the below exception when trying to use `jwt-circe` v3.1.0 with `http4s` v0.20.10. 
This appears be due to the libraries depending on different versions of Circe 0.12.0-M3 vs. 0.11.1.
The code works if I downgrade to `jwt-circe`v3.0 which uses the same Circe version as `http4s`.

Is there a specific reason for using the 0.12 milestone build? Could Circe version be downgraded to the latest release version?

```
java.lang.NoClassDefFoundError: io/circe/jawn/CirceSupportParser$
	at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderAdaptive$1(CirceInstances.scala:60)
	at org.http4s.EntityDecoder$$anon$7.decode(EntityDecoder.scala:176)
	at org.http4s.EntityDecoder$$anon$2.decode(EntityDecoder.scala:43)
	at org.http4s.client.DefaultClient.$anonfun$expectOr$2(DefaultClient.scala:99)
	at cats.effect.Resource.$anonfun$use$1(Resource.scala:120)
	at cats.effect.internals.IOBracket$BracketStart.liftedTree1$1(IOBracket.scala:79)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:79)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: io.circe.jawn.CirceSupportParser$
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 more
```

**Comment by pauldijou** [comment]
The reason is that people kept asking for Scala 2.13 and looks like Circe author is not planning to build older versions for that target. https://repo.maven.apache.org/maven2/io/circe/circe-core_2.13/

If Circe 0.11.1 were to be published for Scala 2.13, I would not mind downgrading its version.

**Comment by travisbrown** [comment]
The problem is that there's no Cats 1.x release for 2.13 (and won't be, because of ScalaCheck), and no non-milestone, non-RC Cats 2.0 yet, and in any case I wouldn't want to bump from Cats 1 to Cats 2 in a patch version update.

**Comment by marko-asplund** [comment]
@pauldijou @travisbrown Thanks for your comments. I guess the workaround in my case would be to just use `jwt-circe` v3.0 for the time being.

**Comment by pauldijou** [comment]
Thanks for the explanation @travisbrown .

@marko-asplund I don't think there has been anything major on the last releases (except a fix for Java 8).

**Comment by marko-asplund** [comment]
@pauldijou Since we are also using Java 11, one more thing just came to mind: would moving the Scala 2.13 changes to 3.1 branch and reverting back to Scala 2.12 & Circe 0.11.1 in the 3.0 branch be an option?

The rationale being to avoid a major dependency change across minor 3.0 releases.

**Comment by pauldijou** [comment]
Use 4.0.0. Changed my mind, will stick to stable releases from now on.

**Comment by marko-asplund** [comment]
Just tested the new release and it seems to be working, closing this issue.
Big thanks @pauldijou! 🥇
