### ISSUE TITLE
JWTClaim.toJson method does not return a valid JSON string

### ISSUE THREAD

**Issue by meglic** [jwt-scala/jwt-scala#142]
Hi,
I am trying to parse claim part of my JWT token by using the JWT.decode method and JWTClaim.toJson method. It seems like I am getting a wrong JSON from JWTClaim.toJson method? I added the example code. Have I missed something or is this a bug? Thx.
```scala
import play.api.libs.json._
import scala.util.Success
import scala.util.Failure
import pdi.jwt._

case class MyJWTToken(iss: String, iat: Int, exp: Int, aud: String, sub: String, a: String, b: BigDecimal)

object MyJWTToken {
  implicit val format: Format[MyJWTToken] = Json.format[MyJWTToken]

  def parseToMyJWTTokenObject(inputJson: String): Option[MyJWTToken] = {
    val jsonString: JsValue = Json.parse(inputJson)
    val qrCodeFromJson: JsResult[MyJWTToken] = Json.fromJson[MyJWTToken](jsonString)
    qrCodeFromJson match {
      case JsSuccess(r: MyJWTToken, path: JsPath) =>
        Some(r)
      case e@JsError(_) =>
        println("Errors: " + JsError.toJson(e).toString())
        None
    }
  }
}




// The working example with valid JSON string - string can be parsed to an object if i remove comma ... please see the log
val testString = "{\"exp\":1597914901,\"iat\":1566378901,\"iss\":\"\",\"aud\":\"\",\"sub\":\"da1b3852-6827-11e9-a923-1681be663d3e\",\"a\":\"da1b3852-6827-11e9-a923-1681be663d3e\",\"b\":123.34}"
println("Working example - valid JSON string it can be parsed")
println("testString: " + testString)

// parse to object
val myJWTToken = MyJWTToken.parseToMyJWTTokenObject(testString)
myJWTToken match {
  case Some(r) =>
    println("Result 1:")
    println("iss: " + r.iss)
    println("iat: " + r.iat)
    println("exp: " + r.exp)
    println("aud: " + r.aud)
    println("sub: " + r.sub)
    println("a: " + r.a)
    println("b: " + r.b)
}


// Non working example by using  "com.pauldijou" %% "jwt-core" % "3.0.1"
/*
myJWTToken - The JSON claim part of the token should looks like this:
  {
   "iss": "",
   "iat": 1566378901,
   "exp": 1597914901,
   "aud": "",
   "sub": "da1b3852-6827-11e9-a923-1681be663d3e",
   "a": "da1b3852-6827-11e9-a923-1681be663d3e",
   "b": 123.34
 }
*/

println("-----------------------------------------------------------------------------------------------------------")
println("Non working example by using  \"com.pauldijou\" %% \"jwt-core\" % \"3.0.1 -> JSON string from JWTClaim.toJson method?")
//can be checked at jwt.io
val myTokenEncoded = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiIiLCJpYXQiOjE1NjYzNzg5MDEsImV4cCI6MTU5NzkxNDkwMSwiYXVkIjoiIiwic3ViIjoiZGExYjM4NTItNjgyNy0xMWU5LWE5MjMtMTY4MWJlNjYzZDNlIiwiYSI6ImRhMWIzODUyLTY4MjctMTFlOS1hOTIzLTE2ODFiZTY2M2QzZSIsImIiOjEyMy4zNH0.8upl7OlK9a4UrfFu-hHWW_pdH1Q_zV1tffXsrmXDoCeRtS35W5vK8FqfAawTagc9zU6Rrq175UGkkHkJfi8_Rw"
Jwt.decode(myTokenEncoded, "qwertyuiopasdfghjklzxcvbnm123456", Seq(JwtAlgorithm.HS512)) match {
  case Success(claim) =>

    // Stringify as JSON from JWTClaim.toJson --> method does not return a valid JSON string or did I miss something here?
    // Please see the log
    println("JWTClaim.toJson: " + claim.toJson)
    val myJWTToken1 = MyJWTToken.parseToMyJWTTokenObject(claim.toJson)
    myJWTToken1 match {
      case Some(r) =>
        println("iss: " + r.iss)
        println("iat: " + r.iat)
        println("exp: " + r.exp)
        println("aud: " + r.aud)
        println("sub: " + r.sub)
        println("a: " + r.a)
        println("b: " + r.b)
    }

  case Failure(f) => println(f)
}



```
The console output. I am getting the com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)):
```log
Working example - valid JSON string it can be parsed
testString: {"exp":1597914901,"iat":1566378901,"iss":"","aud":"","sub":"da1b3852-6827-11e9-a923-1681be663d3e","a":"da1b3852-6827-11e9-a923-1681be663d3e","b":123.34}

myJWTToken: Option[MyJWTToken] = Some(MyJWTToken(,1566378901,1597914901,,da1b3852-6827-11e9-a923-1681be663d3e,da1b3852-6827-11e9-a923-1681be663d3e,123.34))
Result 1:
iss:
iat: 1566378901
exp: 1597914901
aud:
sub: da1b3852-6827-11e9-a923-1681be663d3e
a: da1b3852-6827-11e9-a923-1681be663d3e
b: 123.34


-----------------------------------------------------------------------------------------------------------
Non working example by using  "com.pauldijou" %% "jwt-core" % "3.0.1 -> JSON string from JWTClaim.toJson method?
myTokenEncoded: String = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiIiLCJpYXQiOjE1NjYzNzg5MDEsImV4cCI6MTU5NzkxNDkwMSwiYXVkIjoiIiwic3ViIjoiZGExYjM4NTItNjgyNy0xMWU5LWE5MjMtMTY4MWJlNjYzZDNlIiwiYSI6ImRhMWIzODUyLTY4MjctMTFlOS1hOTIzLTE2ODFiZTY2M2QzZSIsImIiOjEyMy4zNH0.8upl7OlK9a4UrfFu-hHWW_pdH1Q_zV1tffXsrmXDoCeRtS35W5vK8FqfAawTagc9zU6Rrq175UGkkHkJfi8_Rw
JWTClaim.toJson: {"exp":1597914901,"iat":1566378901,"iss":"",,"aud":"","sub":"da1b3852-6827-11e9-a923-1681be663d3e","a":"da1b3852-6827-11e9-a923-1681be663d3e","b":123.34}
com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): was expecting double-quote to start field name
at [Source: (String)"{"exp":1597914901,"iat":1566378901,"iss":"",,"aud":"","sub":"da1b3852-6827-11e9-a923-1681be663d3e","a":"da1b3852-6827-11e9-a923-1681be663d3e","b":123.34}"; line: 1, column: 46]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1767)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:692)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:199)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:126)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:121)
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:255)
at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:16)
at play.api.libs.json.Json$.parse(Json.scala:171)
at MyJWTToken$.parseToMyJWTTokenObject(<console>:26)
... 38 elided
```

**Comment by pauldijou** [comment]
This looks like a bug in the pure Scala Jwt. I will fix it ASAP but you probably want to use `JwtJson.decode` instead of `Jwt.decode` since you are using this lib. It will be way safer than my quick regexp for pure Scala implementation.

**Comment by meglic** [comment]
I have tried with `JwtJson.decode` and it works like a charm. Thank you Paul. Great work!
