### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0

### ISSUE THREAD

**Issue by phelps-sg** [jwt-scala/jwt-scala#410]
Issue #403 is still unresolved with version of 9.1.1 of jwt-scala.

A simple play project which reproduces the problem can be found here: https://github.com/phelps-sg/scala-api-sample/tree/jwt_scala_compatibility.  Note that you need to checkout the `jwt_scala_compatibility` branch of the aforementioned project.

Running the above application gives the following run-time error:

~~~
(base) sphelps@pop-os:~/vcs/coding/scala-api-sample$ sbt clean run
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 11.0.12)
[info] loading global plugins from /home/sphelps/.sbt/1.0/plugins
[info] loading settings for project scala-api-sample-build from plugins.sbt,scaffold.sbt ...
[info] loading project definition from /home/sphelps/vcs/coding/scala-api-sample/project
[info] loading settings for project root from build.sbt ...
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info] 
[info] Version 2.8.16 running Java 11.0.12
[info] 
[info] Play is run entirely by the community. Please consider contributing and/or donating:
[info] https://www.playframework.com/sponsors
[info] 
[success] Total time: 0 s, completed 2 Oct 2022, 11:03:27

--- (Running the application, auto-reloading is enabled) ---

[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:853)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:242)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:241)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.configureObjectMapperModules(JacksonObjectMapperProvider.scala:241)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.createObjectMapper(JacksonObjectMapperProvider.scala:265)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.create(JacksonObjectMapperProvider.scala:359)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.$anonfun$getOrCreate$1(JacksonObjectMapperProvider.scala:317)
[error]         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.getOrCreate(JacksonObjectMapperProvider.scala:317)
[error]         at akka.serialization.jackson.JacksonJsonSerializer.<init>(JacksonSerializer.scala:141)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
[error]         at scala.util.Try$.apply(Try.scala:210)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
[error]         at scala.util.Success.flatMap(Try.scala:258)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:396)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:392)
[error]         at scala.util.Failure.recoverWith(Try.scala:240)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:392)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:390)
[error]         at scala.util.Failure.recoverWith(Try.scala:240)
[error]         at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
[error]         at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
[error]         at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
[error]         at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2360)
[error]         at scala.collection.immutable.HashMap$.from(HashMap.scala:2182)
[error]         at scala.collection.immutable.HashMap$.from(HashMap.scala:2158)
[error]         at scala.collection.MapOps$WithFilter.map(Map.scala:381)
[error]         at akka.serialization.Serialization.<init>(Serialization.scala:424)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
[error]         at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1165)
[error]         at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1208)
[error]         at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
[error]         at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1202)
[error]         at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1221)
[error]         at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1042)
[error]         at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1029)
[error]         at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1029)
[error]         at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1052)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:290)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:291)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:100)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:83)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:107)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.reflect.InvocationTargetException
[error] Total time: 2 s, completed 2 Oct 2022, 11:03:30
~~~

**Comment by phelps-sg** [comment]
Actually, this looks like a problem with jwks-rsa which depends on the latest version of jackson (2.13.2) whereas play depends on 2.11.4:

~~~
[info] com.example:scala-api-sample_2.13:1.0-SNAPSHOT [S]
[info]   +-com.auth0:jwks-rsa:0.21.1
[info]   | +-com.fasterxml.jackson.core:jackson-databind:2.13.2.2
[info]   | | +-com.fasterxml.jackson.core:jackson-annotations:2.13.2
[info]   | | +-com.fasterxml.jackson.core:jackson-core:2.13.2
[info]   | | 
[info]   | +-com.google.guava:guava:30.0-jre (evicted by: 30.1.1-jre)
[info]   | +-com.google.guava:guava:30.1.1-jre
[info]   |   +-com.google.code.findbugs:jsr305:3.0.2
[info]   |   +-com.google.errorprone:error_prone_annotations:2.5.1
[info]   |   +-com.google.guava:failureaccess:1.0.1
[info]   |   +-com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-..
[info]   |   +-com.google.j2objc:j2objc-annotations:1.3
[info]   |   +-org.checkerframework:checker-qual:3.8.0
[info]   |   
[info]   +-com.github.jwt-scala:jwt-core_2.13:9.1.1 [S]
[info]   +-com.github.jwt-scala:jwt-play_2.13:9.1.1 [S]
[info]   | +-com.github.jwt-scala:jwt-play-json_2.13:9.1.1 [S]
[info]   | | +-com.github.jwt-scala:jwt-json-common_2.13:9.1.1 [S]
[info]   | | | +-com.github.jwt-scala:jwt-core_2.13:9.1.1 [S]
[info]   | | | 
[info]   | | +-com.typesafe.play:play-json_2.13:2.9.3 [S]
[info]   | |   +-com.fasterxml.jackson.core:jackson-annotations:2.11.4 (evicted by: 2..
[info]   | |   +-com.fasterxml.jackson.core:jackson-annotations:2.13.2
[info]   | |   +-com.fasterxml.jackson.core:jackson-core:2.11.4 (evicted by: 2.13.2)
[info]   | |   +-com.fasterxml.jackson.core:jackson-core:2.13.2
[info]   | |   +-com.fasterxml.jackson.core:jackson-databind:2.11.4 (evicted by: 2.13..
[info]   | |   +-com.fasterxml.jackson.core:jackson-databind:2.13.2.2
[info]   | |   | +-com.fasterxml.jackson.core:jackson-annotations:2.13.2
[info]   | |   | +-com.fasterxml.jackson.core:jackson-core:2.13.2
[info]   | |   | 
~~~

**Comment by minnieshi** [comment]
for those who wondered how above was derived (run sbt dependencyTree will find the pulled in dependencies)
