### ISSUE TITLE
NoSuchMethodError when creating JWT cookie with Gatling

### ISSUE THREAD

**Issue by MikeMolIS** [jwt-scala/jwt-scala#53]
When I try to create a cookie, part of a simulation, I get a NoSuchMethodError.

My code looks like this:
```scala
def getJWTCookie: String = {
    Jwt.encode("""{"user":1}""", "secretKey", JwtAlgorithm.HS256)
  }
```
I compile the code with the Zinc compiler of Gatling. I also tried to compile the code with the scala-maven-plugin. It also gave the same result.

The stacktrace:
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at pdi.jwt.JwtAlgorithm$HS256$.<init>(JwtAlgorithm.scala:65)
        at pdi.jwt.JwtAlgorithm$HS256$.<clinit>(JwtAlgorithm.scala)
        at nl.translink.util.CookieUtil.getJWTCookie(CookieUtil.scala:7)
        at nl.translink.simulations.FEAPIGatewaySimulation.<init>(FEAPIGatewaySimulation.scala:11)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at io.gatling.app.Runner.run0(Runner.scala:79)
        at io.gatling.app.Runner.run(Runner.scala:64)
        at io.gatling.app.Gatling$.start(Gatling.scala:56)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:41)
        at io.gatling.app.Gatling$.main(Gatling.scala:33)
        at io.gatling.app.Gatling.main(Gatling.scala)
        ... 6 more
```
Can you look at it please?

Thanks, Mike

**Comment by pauldijou** [comment]
Which version are you using? I had kind of the same problem when generating the project documentation but it's fixed in the last version.

**Comment by MikeMolIS** [comment]
I tried it with jwt-core_2.12 version 0.12.1 and with 0.10.0

**Comment by pauldijou** [comment]
Ok, I quickly tried to reproduce but couldn't. I don't have much time to do any Scala right now and I have never used Gatling.

You can try to debug on your side or setup a small project to reproduce and I will try to find some time to debug it.
