### ISSUE TITLE
Exception in thread "main" java.lang.AbstractMethodError: pdi.jwt.JwtBase64$.pdi$jwt$JwtBase64Impl$$encoder()Ljava/util/Base64$Encoder;

### ISSUE THREAD

**Issue by YouXiang-Wang** [jwt-scala/jwt-scala#66]
```
  def generateToken(clientId: String): String = {

    val token = Jwt.encode("""{"user":1}""", "secretKey", JwtAlgorithm.HS256)
    token
    ""
  }
```

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=57008:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar:/Users/wangyoux/dev/Microservice/message-service/target/scala-2.11/classes:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.5/scala-parser-combinators_2.11-1.0.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.11/0.8.0/scala-java8-compat_2.11-0.8.0.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/javax.inject/javax.inject/1/jars/javax.inject.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/shaded-oauth/1.0.4/shaded-oauth-1.0.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/shaded-asynchttpclient/1.0.4/shaded-asynchttpclient-1.0.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-ws-standalone_2.11/1.0.4/play-ws-standalone_2.11-1.0.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-ahc-ws-standalone_2.11/1.0.4/play-ahc-ws-standalone_2.11-1.0.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/cachecontrol_2.11/1.1.2/cachecontrol_2.11-1.1.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.11/0.2.2/ssl-config-core_2.11-0.2.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.10/2.7.2/jackson-module-scala_2.10-2.7.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.7.2/jackson-module-paranamer-2.7.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/pcollections/pcollections/2.1.2/pcollections-2.1.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/nulab-inc/scala-oauth2-core_2.11/1.3.0/scala-oauth2-core_2.11-1.3.0.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/com.google.guava/guava/19.0/bundles/guava.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/com.google.code.findbugs/jsr305/1.3.9/jars/jsr305.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/cb372/scalacache-guava_2.11/0.9.4/scalacache-guava_2.11-0.9.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/cb372/scalacache-core_2.11/0.9.4/scalacache-core_2.11-0.9.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/igl/jwt_2.11/1.2.0/jwt_2.11-1.2.0.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/commons-codec/commons-codec/1.10/jars/commons-codec.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.11/2.5.3/akka-stream_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.11/2.5.3/akka-slf4j_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-remote_2.11/2.5.3/akka-remote_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.11/2.5.3/akka-protobuf_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-persistence_2.11/2.5.3/akka-persistence_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-distributed-data_2.11/2.5.3/akka-distributed-data_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-contrib_2.11/2.5.3/akka-contrib_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-cluster_2.11/2.5.3/akka-cluster_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-cluster-tools_2.11/2.5.3/akka-cluster-tools_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-cluster-sharding_2.11/2.5.3/akka-cluster-sharding_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-agent_2.11/2.5.3/akka-agent_2.11-2.5.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.5.3/akka-actor_2.11-2.5.3.jar:/Users/wangyoux/.ivy2/local/org.parasol.service/http-service_2.11/1.0/jars/http-service_2.11.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-runtime-registry/1.5.5/protostuff-runtime-registry-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-runtime/1.5.5/protostuff-runtime-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-json/1.5.5/protostuff-json-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-core/1.5.5/protostuff-core-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-collectionschema/1.5.5/protostuff-collectionschema-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/protostuff/protostuff-api/1.5.5/protostuff-api-1.5.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.14/jffi-1.2.14.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.14/jffi-1.2.14-native.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jnr-constants/0.9.6/jnr-constants-0.9.6.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jnr-ffi/2.1.2/jnr-ffi-2.1.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/scopt/scopt_2.11/3.4.0/scopt_2.11-3.4.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.3.1/config-1.3.1.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.11/10.0.7/akka-http-core_2.11-10.0.7.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-http-spray-json_2.11/10.0.0/akka-http-spray-json_2.11-10.0.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.11/10.0.7/akka-http_2.11-10.0.7.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.11/10.0.7/akka-parsing_2.11-10.0.7.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/commons-logging/commons-logging/1.2/jars/commons-logging.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/aeron/aeron-client/1.2.5/aeron-client-1.2.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/aeron/aeron-driver/1.2.5/aeron-driver-1.2.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/io/spray/spray-json_2.11/1.3.2/spray-json_2.11-1.3.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/me/maciejb/etcd-client/etcd-client_2.11/0.2.0/etcd-client_2.11-0.2.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/agrona/Agrona/0.9.5/agrona-0.9.5.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.apache.httpcomponents/httpclient/4.5.2/jars/httpclient.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.apache.httpcomponents/httpcore/4.4.4/jars/httpcore.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.joda/joda-convert/1.8.1/jars/joda-convert.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/lmdbjava/lmdbjava/0.0.5/lmdbjava-0.0.5.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar:/Users/wangyoux/.ivy2/local/org.parasol.service/service-common-core_2.11/1.0/jars/service-common-core_2.11.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.reactivestreams/reactive-streams/1.0.0/jars/reactive-streams.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.scala-lang/scala-library/2.11.8/jars/scala-library.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/org.scala-lang/scala-reflect/2.11.8/jars/scala-reflect.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-stm/scala-stm_2.11/0.8/scala-stm_2.11-0.8.jar:/Users/wangyoux/.ivy2/local/org.parasol.service/service-data-provider_2.11/1.0/jars/service-data-provider_2.11.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.9/jackson-core-asl-1.9.9.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.9/jackson-mapper-asl-1.9.9.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/keycloak/keycloak-adapter-core/1.6.1.Final/keycloak-adapter-core-1.6.1.Final.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/keycloak/keycloak-common/1.6.1.Final/keycloak-common-1.6.1.Final.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/keycloak/keycloak-core/1.6.1.Final/keycloak-core-1.6.1.Final.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-core-impl_2.11/0.14.0/jwt-core-impl_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-core-legacy-impl_2.11/0.14.0/jwt-core-legacy-impl_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-core-legacy_2.11/0.14.0/jwt-core-legacy_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-core_2.11/0.14.0/jwt-core_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-json-common-legacy_2.11/0.14.0/jwt-json-common-legacy_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-play-json-legacy_2.11/0.14.0/jwt-play-json-legacy_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/pauldijou/jwt-play_2.11/0.14.0/jwt-play_2.11-0.14.0.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.57/bcpkix-jdk15on-1.57.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.57/bcprov-jdk15on-1.57.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/ch.qos.logback/logback-classic/1.1.7/jars/logback-classic.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/ch.qos.logback/logback-core/1.1.7/jars/logback-core.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.7.2/jackson-annotations-2.7.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.7.2/jackson-core-2.7.2.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.2/jackson-databind-2.7.2.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.7.1/bundles/jackson-datatype-jdk8.jar:/Users/wangyoux/dev/activator-dist-1.3.12/repository/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.7.1/bundles/jackson-datatype-jsr310.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-datacommons_2.11/2.5.4/play-datacommons_2.11-2.5.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-functional_2.11/2.5.4/play-functional_2.11-2.5.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-iteratees_2.11/2.5.4/play-iteratees_2.11-2.5.4.jar:/Users/wangyoux/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-json_2.11/2.5.4/play-json_2.11-2.5.4.jar parasol.gateway.router.http.sso.oauth2.token.TokenProvider
objc[4061]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.AbstractMethodError: pdi.jwt.JwtBase64$.pdi$jwt$JwtBase64Impl$$encoder()Ljava/util/Base64$Encoder;
	at pdi.jwt.JwtBase64Impl$class.encodeString(JwtBase64Impl.scala:15)
	at pdi.jwt.JwtBase64$.encodeString(JwtBase64.scala:3)
	at pdi.jwt.JwtBase64$.encodeString(JwtBase64.scala:13)
	at pdi.jwt.JwtCore$class.encode(Jwt.scala:79)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at pdi.jwt.JwtCore$class.encode(Jwt.scala:109)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at parasol.gateway.router.http.sso.oauth2.token.AccessTokenGenerator$class.generateToken(AccessTokenGenerator.scala:81)
	at parasol.gateway.router.http.sso.oauth2.token.AccessTokenGenerator$.generateToken(AccessTokenGenerator.scala:91)
	at parasol.gateway.router.http.sso.oauth2.token.TokenProvider$.delayedEndpoint$parasol$gateway$router$http$sso$oauth2$token$TokenProvider$1(AccessTokenGenerator.scala:95)
	at parasol.gateway.router.http.sso.oauth2.token.TokenProvider$delayedInit$body.apply(AccessTokenGenerator.scala:93)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at parasol.gateway.router.http.sso.oauth2.token.TokenProvider$.main(AccessTokenGenerator.scala:93)
	at parasol.gateway.router.http.sso.oauth2.token.TokenProvider.main(AccessTokenGenerator.scala)
```

**Comment by pauldijou** [comment]
To be honest, I have no idea what's happening...

**Comment by YouXiang-Wang** [comment]
The libs are:
scalaVersion := "2.11.8"

lazy val jwtCore = "com.pauldijou" %% "jwt-core" % "0.14.0"

lazy val jwtJson = "com.pauldijou" %% "jwt-play" % "0.14.0"

**Comment by pauldijou** [comment]
You only need one of those, `lazy val jwtJson = "com.pauldijou" %% "jwt-play" % "0.14.0"`. It will automatically import `core` on its own.
