### ISSUE TITLE
sbt compilation failure

### ISSUE THREAD

**Issue by evbo** [jwt-scala/jwt-scala#82]
Hi, I would like to contribute a PR but am getting this error when compiling:

```
jwt-scala(master)$ sbt compile
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /git/jwt-scala/project
[info] Loading settings from build.sbt ...
[info] Resolving key references (15488 settings) ...
usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...
[error] java.util.NoSuchElementException: head of empty stream
[error]         at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1104)
[error]         at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1102)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:138)
[error]         at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:810)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:202)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:219)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] java.util.NoSuchElementException: head of empty stream
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

Any idea what it could be?

```
sbt -v
[process_args] java_version = '1.8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/libs/sbt-1.1.1/bin/sbt-launch.jar

```

**Comment by pauldijou** [comment]
Which Git version are you using? Try updating it maybe...

**Comment by evbo** [comment]
Exactly the problem. Using git 2.7.2 and issue is gone.

**Comment by radumanolescu** [comment]
I am having the exact same problem on Red Hat Linux 2.6 , git version 2.9.5, sbt 1.2.1. What can I do to fix this?

**Comment by pauldijou** [comment]
@radumanolescu 	I have no idea myself... It looks like an sbt problem to me. Have you tried opening an issue on their repo?

**Comment by radumanolescu** [comment]
@pauldijou I made sure I was running bash (not /bin/sh) and the version of git was >= 2.7.2
