### ISSUE TITLE
sbt testAll fails on master

### ISSUE THREAD

**Issue by evbo** [jwt-scala/jwt-scala#83]
I am able to compile but get the following error running tests on master with `sbt testAll`. Any idea what could be causing this? I tried wiping out my ~/.ivy2/cache and trying again but this issue persists:

```
[info] pdi.jwt.JwtSpec *** ABORTED ***
[info]   java.lang.LinkageError: loader constraint violation: when resolving method "mockit.internal.state.MockClasses.findPreviouslyAppliedMockUps(Lmockit/MockUp;)Lmockit/internal/state/MockClasses$MockUpInstances;" the class loader (instance of sbt/internal/inc/classpath/ClasspathUtilities$$anon$1) of the current class, mockit/MockUp, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, mockit/internal/state/MockClasses, have different Class objects for the type mockit/MockUp used in the signature
[info]   at mockit.MockUp.findPreviouslyMockedClassIfMockUpAlreadyApplied(MockUp.java:159)
[info]   at mockit.MockUp.<init>(MockUp.java:118)
[info]   at pdi.jwt.TimeFixtureImpl$$anon$1.<init>(TimeFixtureImpl.scala:9)
[info]   at pdi.jwt.TimeFixtureImpl.mockTime(TimeFixtureImpl.scala:9)
[info]   at pdi.jwt.TimeFixtureImpl.mockTime$(TimeFixtureImpl.scala:8)
[info]   at pdi.jwt.JwtSpec.mockTime(JwtSpec.scala:10)
[info]   at pdi.jwt.Fixture.mockValidTime(Fixture.scala:57)
[info]   at pdi.jwt.Fixture.mockValidTime$(Fixture.scala:57)
[info]   at pdi.jwt.JwtSpec.mockValidTime(JwtSpec.scala:10)
[info]   at pdi.jwt.JwtSpec.$anonfun$new$3(JwtSpec.scala:26)
[info]   ...
[error] java.lang.LinkageError: loader constraint violation: when resolving method "mockit.internal.state.MockClasses.findPreviouslyAppliedMockUps(Lmockit/MockUp;)Lmockit/internal/state/MockClasses$MockUpInstances;" the class loader (instance of sbt/internal/inc/classpath/ClasspathUtilities$$anon$1) of the current class, mockit/MockUp, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, mockit/internal/state/MockClasses, have different Class objects for the type mockit/MockUp used in the signature
[error]         at mockit.MockUp.findPreviouslyMockedClassIfMockUpAlreadyApplied(MockUp.java:159)
[error]         at mockit.MockUp.<init>(MockUp.java:118)
[error]         at pdi.jwt.TimeFixtureImpl$$anon$1.<init>(TimeFixtureImpl.scala:9)
[error]         at pdi.jwt.TimeFixtureImpl.mockTime(TimeFixtureImpl.scala:9)
[error]         at pdi.jwt.TimeFixtureImpl.mockTime$(TimeFixtureImpl.scala:8)
[error]         at pdi.jwt.JwtSpec.mockTime(JwtSpec.scala:10)
[error]         at pdi.jwt.Fixture.mockValidTime(Fixture.scala:57)
[error]         at pdi.jwt.Fixture.mockValidTime$(Fixture.scala:57)
[error]         at pdi.jwt.JwtSpec.mockValidTime(JwtSpec.scala:10)
[error]         at pdi.jwt.JwtSpec.$anonfun$new$3(JwtSpec.scala:26)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error]         at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error]         at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:22)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:20)
[error]         at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
[error]         at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error]         at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error]         at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
[error]         at org.scalatest.FunSpecLike.invokeWithFixture$1(FunSpecLike.scala:452)
[error]         at org.scalatest.FunSpecLike.$anonfun$runTest$1(FunSpecLike.scala:464)
[error]         at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error]         at org.scalatest.FunSpecLike.runTest(FunSpecLike.scala:464)
[error]         at org.scalatest.FunSpecLike.runTest$(FunSpecLike.scala:446)
[error]         at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
[error]         at org.scalatest.FunSpecLike.$anonfun$runTests$1(FunSpecLike.scala:497)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[error]         at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error]         at org.scalatest.FunSpecLike.runTests(FunSpecLike.scala:497)
[error]         at org.scalatest.FunSpecLike.runTests$(FunSpecLike.scala:496)
[error]         at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
[error]         at org.scalatest.Suite.run(Suite.scala:1147)
[error]         at org.scalatest.Suite.run$(Suite.scala:1129)
[error]         at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
[error]         at org.scalatest.FunSpecLike.$anonfun$run$1(FunSpecLike.scala:501)
[error]         at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error]         at org.scalatest.FunSpecLike.run(FunSpecLike.scala:501)
[error]         at org.scalatest.FunSpecLike.run$(FunSpecLike.scala:500)
[error]         at org.scalatest.FunSpec.run(FunSpec.scala:1630)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[error]         at sbt.TestRunner.runTest$1(TestFramework.scala:106)
[error]         at sbt.TestRunner.run(TestFramework.scala:117)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
[error]         at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[error]         at sbt.TestFunction.apply(TestFramework.scala:271)
[error]         at sbt.Tests$.processRunnable$1(Tests.scala:307)
[error]         at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:313)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (coreCommonLegacy / Test / executeTests) java.lang.LinkageError: loader constraint violation: when resolving method "mockit.internal.state.MockClasses.findPreviouslyAppliedMockUps(Lmockit/MockUp;)Lmockit/internal/state/MockClasses$MockUpInstances;" the class loader (instance of sbt/internal/inc/classpath/ClasspathUtilities$$anon$1) of the current class, mockit/MockUp, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, mockit/internal/state/MockClasses, have different Class objects for the type mockit/MockUp used in the signature
[error] Total time: 9 s, completed Mar 6, 2018 9:30:37 AM

```

**Comment by pauldijou** [comment]
This is [documented](https://github.com/pauldijou/jwt-scala#got-a-problem) (kind of). Run the tests again without closing SBT.
