### ISSUE TITLE
Ensure compatibility with Graal

### ISSUE THREAD

**Issue by mavilein** [jwt-scala/jwt-scala#91]
Hey there,

first of all i would like to thank for developing this software! I am a backend engineer at [Prisma](https://github.com/prismagraphql/prisma). I am opening this issue as we are a happy user of this library and would like it to be compatible with Graal.

**What is Graal?**

Graal is a collection of tools. For one it is a JVM replacement that does not only run Java Bytecode but also other languages like Javascript or Ruby. It also comes with a tool called native image. This allows to **compile a JAR into a standalone binary**.

We would like to turn our Prisma Server into a lightweight binary with Graal.

However the Graal native image tool comes with some limitations. Some features of the JVM are not supported, e.g. the support for reflection is limited because it is not a good fit with ahead of time compilation. Therefore we created a [test suite](https://github.com/prismagraphql/graal-compatibility) to check the compatibility of our used dependencies with Graal. For each dependency we tried to come up with a super small program and see whether it compiles with Graal or not.

The program to test compatibility with this library can be found [here](https://github.com/prismagraphql/graal-compatibility/blob/master/jwt/src/main/scala/Main.scala).

**What's the problem we have hit?**
When running with `-H:+ReportUnsupportedElementsAtRuntime`:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unimplemented(VMErrorSubstitutions.java:103)
	at com.oracle.svm.core.jdk.Target_javax_crypto_JceSecurity.getVerificationResult(SecuritySubstitutions.java:384)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
	at javax.crypto.Mac.getInstance(Mac.java:222)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:121)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:150)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:159)
	at pdi.jwt.JwtCore.encode(Jwt.scala:80)
	at pdi.jwt.JwtCore.encode$(Jwt.scala:78)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at pdi.jwt.JwtCore.encode(Jwt.scala:109)
	at pdi.jwt.JwtCore.encode$(Jwt.scala:108)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at Main$.main(Main.scala:7)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

When running without `-H:+ReportUnsupportedElementsAtRuntime`:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unimplemented(VMErrorSubstitutions.java:103)
	at com.oracle.svm.core.jdk.Target_javax_crypto_JceSecurity.getVerificationResult(SecuritySubstitutions.java:384)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
	at javax.crypto.Mac.getInstance(Mac.java:222)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:121)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:150)
	at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:159)
	at pdi.jwt.JwtCore.encode(Jwt.scala:80)
	at pdi.jwt.JwtCore.encode$(Jwt.scala:78)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at pdi.jwt.JwtCore.encode(Jwt.scala:109)
	at pdi.jwt.JwtCore.encode$(Jwt.scala:108)
	at pdi.jwt.Jwt$.encode(Jwt.scala:23)
	at Main$.main(Main.scala:7)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

**Note**: The Graal compilation terminates on the first encountered error. Therefore there might be more problems that need to be addressed.

**How can incompatibilities with Graal be fixed?**

Here is a [blog post](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) by the Graal team that explains how the native image tool is working and how they were able to compile a server built on top of netty into a binary.

We ran this test with Graal `1.0.0-rc5`. We used `jwt-core` version `0.14.1`.

**Comment by pauldijou** [comment]
@mavilein Thanks for your interest in this lib.

I haven't done any Scala for years now, I'm only doing small bug fixes on this project. I will not try to dive into some deep JVM compilation issues.

If you submit a PR, I will gladly review and merge it though.
